### ISSUE TITLE
Invoke SetSuppressIncludeNotFoundError to ignore errors when headers files are missing

### ISSUE THREAD

**Issue by mkr-plse** [uber/piranha#65]
When header files are missing in the input files to PiranhaObjC, a fatal error is thrown as follows:
```
tests/OptimisticNamed.m:19:10: fatal error: 'TestHeader.h' file not found
#include "TestHeader.h"
         ^~~~~~~~~~~~~~
```
where `OptimisticNamed.m` is updated to include a non-existent `TestHeader.h`. 

The correct fix will be to call [SetSuppressIncludeNotFoundError](https://clang.llvm.org/doxygen/classclang_1_1Preprocessor.html#ac7bafe67fc32e41460855b39d20ff6af) from the Piranha implementation. (see https://github.com/uber/piranha/issues/50#issuecomment-646934862)

**Comment by mkr-plse** [comment]
Fixed in #67.

**Comment by Samhithgb** [comment]
@mkr-plse, I am unfortunately still facing this issue after taking in the recent changes. The error message is :

/Users/samhith/Project/featuremanager/FeatureManager.h:6:9: fatal error: 'WMExchangeAccount.h' file not found
#import "WMExchangeAccount.h"

Does the current fix also consider missing header files inside another header file? Please let me know if there is any workaround I can follow to avoid this.

**Comment by mkr-plse** [comment]
This should ignore all errors related to missing header files. Can you delete the existing `.dylib` and create a new one by run `./generate-dylib.sh` and try? If not, is it possible for you to create a simple reproducer?

**Comment by Samhithgb** [comment]
Hey @mkr-plse, I tried the above suggestion, and although the original error is now gone, I'm now getting the following errors : 

```
/Users/samhith/project/featuremanager/FeatureManager.h:101:29: error: cannot find
      interface declaration for 'NSObject', superclass of 'FeatureManager'
@interface FeatureManager : NSObject
~~~~~~~~~~~~~~~~~~~~~~~~~   
/Users/samhith/project/featuremanager/FeatureManager.h:103:3: error: expected a type
+(BOOL)isAppTypeNew;
  ^
/Users/samhith/project/featuremanager/FeatureManager.h:104:3: error: expected a type
+(BOOL)loadFile;
```
Is there anything I can do to overcome these errors? Let me know if you need more info on this. Thanks!

**Comment by mkr-plse** [comment]
I am closing this as the original problem is resolved. Will continue the discussion in the #74.
